version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A emmerce worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A emmerce beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis